### ISSUE TITLE
Showdown sprites unavailable

### ISSUE THREAD

**Issue by justin-phxm** [Gabb-c/pokenode-ts#1156]
### Version of Pokenode-ts

1.20.0

### Node.js Version

20.9.0

### Operating System

Windows

### Bug Description

The types for this library do not include Showdown under OtherPokemonSprites. 

### Expected Behavior

Accessing Pokemon.sprites.other should have showdown sprites as an option.

### Steps to Reproduce

Open the file node_modules/pokenode-ts/lib/index.d.ts
![image](https://github.com/user-attachments/assets/e21fddfa-b79c-4362-abd3-26e81cec6eda)

**Comment by Gabb-c** [comment]
Hi @justin-phxm, thanks for your input!
Will fix and release it ASAP!
