### ISSUE TITLE
Missing type in Emerald interface

### ISSUE THREAD

**Issue by CasperSocio** [Gabb-c/pokenode-ts#384]
### What version of pokenode-ts are you using?

next

### What version of Node.js are you using?

17.0.1

### What operating system are you using?

macOS

### Describe the Bug

There is a key-value pair missing from the `[src/models/Pokemon/pokemon.ts]/Emerald` interface.

### Expected Behavior

File: `src/models/Pokemon/pokemon.ts`
Line: 340

The key `front_shiny` is missing under the description.

### To Reproduce

Open file `src/models/Pokemon/pokemon.ts` and scroll to line 340.

**Comment by Gabb-c** [comment]
Hey @CasperSocio, thanks for your input!
Fix released in [1.13.0](https://github.com/Gabb-c/pokenode-ts/releases/tag/v1.13.0)
