### ISSUE TITLE
NamedAPIResourceList doesn't allow access to Pokemon's name in results

### ISSUE THREAD

**Issue by technogize** [Gabb-c/pokenode-ts#413]
### What version of pokenode-ts are you using?

1.13.0

### What version of Node.js are you using?

14.17.3

### What operating system are you using?

MacOS

### Describe the Bug

When using the NamedAPIResourceList interface, I cannot access the Pokemon's name (e.g. pokemon.name) in the result array when getting a list of Pokemon (using `listPokemons`). 

This appears to be due to the `results` in NamedAPIResourceList having a union type of  `NamedAPIResource[] | APIResource[];` rather than just `NamedAPIResource[]` as mentioned in the documentation.

TS error: Property 'name' does not exist on type 'APIResource'.

Documentation: https://pokenode-ts-docs-gabb-c.vercel.app/docs/typings/common-typings#named-api-resource-list 

Currently when viewing in **node_modules/pokenode-ts/dist/index.d.ts** :
```
export interface NamedAPIResourceList {
	/** The total number of resources available from this API */
	count: number;
	/** The URL for the next page in the list */
	next: string | null;
	/** The URL for the previous page in the list */
	previous: string | null;
	/** A list of named API resources */
	results: NamedAPIResource[] | APIResource[];
}

### Expected Behavior

```
const api = new PokemonClient();

    api.listPokemons(0, 500)
            .then((pokeData) => {
                console.log(pokeData)
                pokeData.results.filter((pokemon) => {
                    return pokemon.name === 'ditto'
                })
            })
            .catch((error) => {
                console.log('err')
            })
```

pokemon.name should be accessible, it can be seen in the data returned.

### To Reproduce

```
const api = new PokemonClient();

    api.listPokemons(0, 500)
            .then((pokeData) => {
                console.log(pokeData)
                pokeData.results.filter((pokemon) => {
                    return pokemon.name === 'ditto'
                })
            })
            .catch((error) => {
                console.log('err')
            })
```

pokemon.name is throwing a TS error. Exact error: Property 'name' does not exist on type 'APIResource'. Only pokemon.url is accessible.

**Comment by Gabb-c** [comment]
Thanks for your input, @technogize. it will be fixed soon in the next release.
