### ISSUE TITLE
"Generation" is spelt "Generaton" in Move interface

### ISSUE THREAD

**Issue by technogize** [Gabb-c/pokenode-ts#414]
### What version of pokenode-ts are you using?

1.13.0

### What version of Node.js are you using?

14.17.3

### What operating system are you using?

MacOS

### Describe the Bug

"generation" is spelt "generaton" in Move interface. This causes a mismatch in the data incoming from the API as the object property is actually called "generation".

### Expected Behavior

I should be able to access the move data with `move.generation`.

### To Reproduce

Instead I get the following error telling me to use 'generaton' instead.
```
Property 'generation' does not exist on type 'Move'. Did you mean 'generaton'?ts(2551)
[index.d.ts(2089, 2): ]()'generaton' is declared here.

**Comment by Gabb-c** [comment]
Thanks for your input, @technogize. it will be fixed soon in the next release.
