### ISSUE TITLE
Possible typo in documentation for cacheing

### ISSUE THREAD

**Issue by MorganJay** [Gabb-c/pokenode-ts#774]
### What version of pokenode-ts are you using?

1.17.0

### What version of Node.js are you using?

18.12.1

### What operating system are you using?

Windows

### Describe the Bug

![Screenshot (18)](https://user-images.githubusercontent.com/32873262/210459377-77bbb54c-814e-4653-ac12-9fad56fba4a0.png)

Great job so far! Gabb.

I have a documentation issue while reading the cache section, from the part highlighted in the image above, is it meant to be "localStorage"?

I hope I used the right issue template for this. 

### Expected Behavior

The right spelling of "localStorage" for clear understanding of docs 🙂

### To Reproduce

Visit this section of the docs [here](https://pokenode-ts-docs-gabb-c.vercel.app/docs/guides/cache) 🙂

**Comment by Gabb-c** [comment]
Hey @, thanks for your input!
I'm sorry about the delay. Problems with my workstation hehe ; - ;

Currently I'm enhancing some things in pokenode-ts:

- Build system
- Cache of the requests
- Tests
- CI/CD
- Documentation

So this issue documentation typo will vê fixed soon.

**Comment by Gabb-c** [comment]
Fixed in 1.18.0
